// Auto-generated from colors_demo.html.
// DO NOT EDIT.

library colors_demo_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '_from_packages/dartemis_toolbox/widgets/_xcolorselector.dart.dart';
import 'dart:html';
import 'package:web_ui/web_ui.dart';


// Original code


void main() {
  // Enable this to use Shadow DOM in the browser.
  //useShadowDom = true;
  // xtag is null until the end of the event loop (known dart web ui issue)
}

// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(__root);
  __e0 = __root.nodes[1].nodes[3];
  __t.component(new XColorselector()..host = __e0);
  __t.create();
  __t.insert();
}

//# sourceMappingURL=_colors_demo.dart.dart.map