// Auto-generated from ease_graphics.html.
// DO NOT EDIT.

library ease_graphics_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '_from_packages/dartemis_toolbox/widgets/_xfchart.dart.dart';
import 'dart:html';
import 'package:web_ui/web_ui.dart';
import 'package:dartemis_toolbox/ease.dart' as ease;


// Original code


final __changes = new __observe.Observable();

dynamic __$eases = ease.all;
dynamic get eases {
  if (__observe.observeReads) {
    __observe.notifyRead(__changes, __observe.ChangeRecord.FIELD, 'eases');
  }
  return __$eases;
}
set eases(dynamic value) {
  if (__observe.hasObservers(__changes)) {
    __observe.notifyChange(__changes, __observe.ChangeRecord.FIELD, 'eases',
        __$eases, value);
  }
  __$eases = value;
}

/**
 * Learn about the Web UI package by visiting
 * http://www.dartlang.org/articles/dart-web-components/.
 */
void main() {
  // Enable this to use Shadow DOM in the browser.
  //useShadowDom = true;
}

// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  final __html0 = new autogenerated.Element.html('<div class="span3">\n          <h3></h3>\n          <div is="x-fchart"></div>\n          <h3>goback<sub></sub></h3>\n          <div is="x-fchart"></div>\n        </div>');
  var __e7;
  var __t = new autogenerated.Template(__root);
  __e7 = __root.nodes[1].nodes[9];
  __t.loopIterateAttr(__e7, () => eases.keys, ($list, $index, __t) {
    var k = $list[$index];
    var __e1, __e2, __e4, __e5, __e6;
    __e6 = __html0.clone(true);
    __e1 = __e6.nodes[1];
    var __binding0 = __t.contentBind(() => k, false);
    __e1.nodes.add(__binding0);
    __e2 = __e6.nodes[3];
    __t.oneWayBind(() => eases[k], (e) { if (__e2.xtag.fct != e) __e2.xtag.fct = e; }, false, false);
    __t.component(new XFchart()..host = __e2);
    __e4 = __e6.nodes[5].nodes[1];
    var __binding3 = __t.contentBind(() => k, false);
    __e4.nodes.addAll([new autogenerated.Text('('),
        __binding3,
        new autogenerated.Text(')')]);
    __e5 = __e6.nodes[7];
    __t.oneWayBind(() => ease.goback(eases[k]), (e) { if (__e5.xtag.fct != e) __e5.xtag.fct = e; }, false, false);
    __t.component(new XFchart()..host = __e5);
  __t.addAll([new autogenerated.Text('\n        '),
      __e6,
      new autogenerated.Text('\n      ')]);
  });
  __t.create();
  __t.insert();
}

//# sourceMappingURL=_ease_graphics.dart.dart.map